### ISSUE TITLE
[FR] single databases dumps for Postgres should output the database's name in the file output

### ISSUE THREAD

**Issue by USA-RedDragon** [clevyr/kubedb#126]
When running `kubedb dump --pod cluster-0 --dbname <dbname>`, the dump creates a file called `postgres.tar.gz`. Ideally, this should end up as `<dbname>.tar.gz`.

**Comment by gabe565** [comment]
@USA-RedDragon Good idea. The current format is `NAMESPACE_2006-01-02_150405.sql.gz`. Do you think the dbname should be added between the namespace and the date if not blank?

**Comment by USA-RedDragon** [comment]
I would think DBNAME_NAMESPACE_DATE, but I mostly based this on realizing this FR by trying to tab-complete on the dbname after a dump
